package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;

import com.revrobotics.CANSparkMax;
import com.revrobotics.SparkMaxPIDController;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.button.POVButton;


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

    private static RobotContainer m_robotContainer = new RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // The robot's subsystems
    public final Hanger m_hanger = new Hanger();
    public final Storage m_storage = new Storage();
    public final Collection m_collection = new Collection();
    public final Shooter m_shooter = new Shooter();
    public final Drivetrain m_drivetrain = new Drivetrain();

    // Joysticks
    private final XboxController xboxController = new XboxController(0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // A chooser for autonomous commands
    SendableChooser<Command> m_chooser = new SendableChooser<>();

    /**
     * The container for the robot.  Contains subsystems, OI devices, and commands.
    */
    private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
        // SmartDashboard Buttons
        SmartDashboard.putData("Commands/Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Commands/Drive", new Drive(m_drivetrain));
        SmartDashboard.putData("Commands/DriveToggle", new DriveToggle(m_drivetrain));
        SmartDashboard.putData("Commands/Collect", new Collect(m_collection));
        SmartDashboard.putData("Commands/Shoot", new Shoot(m_shooter));
        SmartDashboard.putData("Commands/ExtendHanger", new ExtendHanger(m_hanger));
        SmartDashboard.putData("Commands/RetractHanger", new RetractHanger(m_hanger));
        SmartDashboard.putData("Commands/FlywheelOneIncrease", new FlywheelOneIncrease(m_shooter));
        SmartDashboard.putData("Commands/FlywheelOneDecrease", new FlywheelOneDecrease(m_shooter));
        SmartDashboard.putData("Commands/FlywheelTwoIncrease", new FlywheelTwoIncrease(m_shooter));
        SmartDashboard.putData("Commands/FlywheelTwoDecrease", new FlywheelTwoDecrease(m_shooter));
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

        // Configure the button bindings
        configureButtonBindings();

        // Configure default commands
        m_drivetrain.setDefaultCommand(new Drive(m_drivetrain));
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

        // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        SmartDashboard.putData("Auto Mode", m_chooser);
    }

    public static RobotContainer getInstance() {
        return m_robotContainer;
    }

    /**
     * Use this method to define your button->command mappings.  Buttons can be created by
     * instantiating a {@link GenericHID} or one of its subclasses ({@link
     * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
     * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
     */
    private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
        // Create some buttons
        final JoystickButton backButton = new JoystickButton(xboxController, XboxController.Button.kBack.value);
        backButton.whenPressed(new DriveToggle(m_drivetrain), true);

        final JoystickButton rightBumper = new JoystickButton(xboxController, XboxController.Button.kRightBumper.value);        
        rightBumper.toggleWhenPressed(new Collect(m_collection), true);

        final JoystickButton leftBumper = new JoystickButton(xboxController, XboxController.Button.kLeftBumper.value);        
        leftBumper.toggleWhenPressed(new Shoot(m_shooter), true);

        final JoystickButton yButton = new JoystickButton(xboxController, XboxController.Button.kY.value);        
        yButton.whileHeld(new ExtendHanger(m_hanger), true);

        final JoystickButton aButton = new JoystickButton(xboxController, XboxController.Button.kA.value);        
        aButton.whileHeld(new RetractHanger(m_hanger), true);

        final POVButton up = new POVButton(xboxController, 0);
        up.whileHeld(new FlywheelOneIncrease(m_shooter), true);

        final POVButton down = new POVButton(xboxController, 180);
        down.whileHeld(new FlywheelOneDecrease(m_shooter), true);

        final POVButton left = new POVButton(xboxController, 90);
        left.whileHeld(new FlywheelTwoDecrease(m_shooter), true);

        final POVButton right = new POVButton(xboxController, 270);
        right.whileHeld(new FlywheelTwoIncrease(m_shooter), true);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public XboxController getXboxController() {
        return xboxController;
    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    /**
     * Use this to pass the autonomous command to the main {@link Robot} class.
     *
     * @return the command to run in autonomous
     */
    public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
        return m_chooser.getSelected();
    }

    public static SparkMaxPIDController getDefaultPIDController(CANSparkMax motor) {
        SparkMaxPIDController pid_controller = motor.getPIDController();

        pid_controller.setP(6e-5);
        pid_controller.setI(0);
        pid_controller.setD(0);
        pid_controller.setOutputRange(-1, 1);

        return pid_controller;
    }
}
